DA v2: Modularization Fix table syncer circular dependencies (#744)
### Feature or Bugfix
<!-- please choose -->
- Bugfix

### Detail
- Circular dependency on GlossaryRepository class causing table-syncer
ECS Task Failure
  - Error Pasted Below:
```
File "/dataall/modules/datasets/tasks/tables_syncer.py", line 12, in <module>
--
from dataall.modules.datasets.services.dataset_table_service import DatasetTableService
File "/dataall/modules/datasets/services/dataset_table_service.py", line 4, in <module>
from dataall.modules.catalog.db.glossary_repositories import GlossaryRepository
File "/dataall/modules/catalog/db/glossary_repositories.py", line 9, in <module>
from dataall.modules.catalog.api.registry import GlossaryRegistry
File "/dataall/modules/catalog/api/__init__.py", line 1, in <module>
from . import (
File "/dataall/modules/catalog/api/queries.py", line 2, in <module>
from dataall.modules.catalog.api.resolvers import (
File "/dataall/modules/catalog/api/resolvers.py", line 2, in <module>
from dataall.modules.catalog.services.glossaries_service import GlossariesService
File "/dataall/modules/catalog/services/glossaries_service.py", line 6, in <module>
from dataall.modules.catalog.db.glossary_repositories import GlossaryRepository
ImportError: cannot import name 'GlossaryRepository' from partially initialized module 'dataall.modules.catalog.db.glossary_repositories' (most likely due to a circular import) (/dataall/modules/catalog/db/glossary_repositories.py)
```

- Moved GlossaryRegistry to a new parent directory to avoid
`/dataall/modules/catalog/api/__init__.py` and importing
GlossariesServices

### Relates
- NA

### Security
Please answer the questions below briefly where applicable, or write
`N/A`. Based on
[OWASP 10](https://owasp.org/Top10/en/).

NA
```
- Does this PR introduce or modify any input fields or queries - this includes
fetching data from storage outside the application (e.g. a database, an S3 bucket)?
  - Is the input sanitized?
  - What precautions are you taking before deserializing the data you consume?
  - Is injection prevented by parametrizing queries?
  - Have you ensured no `eval` or similar functions are used?
- Does this PR introduce any functionality or component that requires authorization?
  - How have you ensured it respects the existing AuthN/AuthZ mechanisms?
  - Are you logging failed auth attempts?
- Are you using or adding any cryptographic features?
  - Do you use a standard proven implementations?
  - Are the used keys controlled by the customer? Where are they stored?
- Are you introducing any new policies/roles/users?
  - Have you used the least-privilege principle? How?
```

By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.